<!--Header-->
<div>
    <div class="row" style="color: #4D4D4D;font-size: 15px;padding-bottom: 20px">
        <div class="col-md-7">
            <img src="http://materials.cv.uoc.edu/cdocent/common/img/logo-uoc.png" alt="Logo UOC" class="img-responsive" style="margin:20px 0px 0px">
        </div>
        <div class="col-md-5">
            <h1 style="margin:15px 0px 0px;font-size: 40px;">Lectura i escriptura de fitxers de dades</h1>
            <div style="text-align:left;margin-top: 5px;"></div>
        </div>
    </div>
    <div class="row" style="background: #FCB517;padding: 10px 20px;">
        <div class="col-md-6">
            <div>PID_00233252</div>
        </div>
        <div class="col-md-6">
            <div style="text-align:right;">Autor: Xavier Duran Albareda <span style="margin-left: 30px;">Coordinació: Julià Minguillón</span></div>
        </div>
    </div>
</div>
<!--/Header-->

# Introducció

L'exporació, manipulació, visualització i anàlisi de dades comença amb la càrrega de les dades des de diferents formats de fitxers. En aquesta activitat veurem com llegir fitxers de tipus `CSV` i `Excel`, carregar-los en un `DataFrame` i tornar-los a guardar en un altre fitxer.

Farem servir les llibreries [`readr`](https://readr.tidyverse.org) i [`readxl`](https://readxl.tidyverse.org), que formen part de la col·lecció de paquets [`tidyverse`](https://tidyverse.org/).

<br>
<div class="row">
     <div class="col-sm-3">
        <img src="images/readr.png" alt="readr">
    </div>
     <div class="col-sm-3">
        <img src="images/readxl.png" alt="readxl">
    </div>
</div>

## Fitxers CSV

L'acrònim `CSV` correspon a _Comma Separated Values_, és a dir, fitxers separats per comes. De fet, veurem que la funció de `pandas` que farem servir per llegir aquests tipus de fitxers també serveix per llegir fitxers separats per altres caracters, com els `TSV` o _Tab-Separated Values_, o els fitxers separats per punt i coma.

El fitxer `CSV` que llegirem correspon al dataset de la competició [Titanic: Machine Learning from Disaster](https://www.kaggle.com/c/titanic) de [Kaggle](https://www.kaggle.com/).

Per llegir un fitxer `CSV` farem servir la funció [`read_csv`](https://readr.tidyverse.org/reference/read_delim.html) de `readr`.

In [1]:
library(readr)
df <- read_csv("data/titanic.csv")
df

Parsed with column specification:
cols(
  PassengerId = col_integer(),
  Survived = col_integer(),
  Pclass = col_integer(),
  Name = col_character(),
  Sex = col_character(),
  Age = col_double(),
  SibSp = col_integer(),
  Parch = col_integer(),
  Ticket = col_character(),
  Fare = col_double(),
  Cabin = col_character(),
  Embarked = col_character()
)

    PassengerId Survived Pclass
1    1          0        3
2    2          1        1
3    3          1        3
4    4          1        1
5    5          0        3
6    6          0        3
7    7          0        1
8    8          0        3
9    9          1        3
10  10          1        2
11  11          1        3
12  12          1        1
13  13          0        3
14  14          0        3
15  15          0        3
16  16          1        2
17  17          0        3
18  18          1        2
19  19          0        3
20  20          1        3
21  21          0        2
22  22          1        2
23  23          1        3
24  24          1        1
25  25          0        3
26  26          1        3
27  27          0        3
28  28          0        1
29  29          1        3
30  30          0        3
⋮   ⋮           ⋮        ⋮
862 862         0        2
863 863         1        1
864 864         0        3
865 865         0        2
866 866         1        2
867 867         1        2
868 868         0        1
869 869         0        3
870 870         1        3
871 871         0        3
872 872         1        1
873 873         0        1
874 874         0        3
875 875         1        2
876 876         1        3
877 877         0        3
878 878         0        3
879 879         0        3
880 880         1        1
881 881         1        2
882 882         0        3
883 883         0        3
884 884         0        2
885 885         0        3
886 886         0        3
887 887         0        2
888 888         1        1
889 889         0        3
890 890         1        1
891 891         0        3
    Name                                                      Sex    Age SibSp
1   Braund, Mr. Owen Harris                                   male   22  1
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)       female 38  1
3   Heikkinen, Miss. Laina                                    female 26  0
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35  1
5   Allen, Mr. William Henry                                  male   35  0
6   Moran, Mr. James                                          male   NA  0
7   McCarthy, Mr. Timothy J                                   male   54  0
8   Palsson, Master. Gosta Leonard                            male    2  3
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27  0
10  Nasser, Mrs. Nicholas (Adele Achem)                       female 14  1
11  Sandstrom, Miss. Marguerite Rut                           female  4  1
12  Bonnell, Miss. Elizabeth                                  female 58  0
13  Saundercock, Mr. William Henry                            male   20  0
14  Andersson, Mr. Anders Johan                               male   39  1
15  Vestrom, Miss. Hulda Amanda Adolfina                      female 14  0
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55  0
17  Rice, Master. Eugene                                      male    2  4
18  Williams, Mr. Charles Eugene                              male   NA  0
19  Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)   female 31  1
20  Masselmani, Mrs. Fatima                                   female NA  0
21  Fynney, Mr. Joseph J                                      male   35  0
22  Beesley, Mr. Lawrence                                     male   34  0
23  McGowan, Miss. Anna "Annie"                               female 15  0
24  Sloper, Mr. William Thompson                              male   28  0
25  Palsson, Miss. Torborg Danira                             female  8  3
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38  1
27  Emir, Mr. Farred Chehab                                   male   NA  0
28  Fortune, Mr. Charles Alexander                            male   19  3
29  O'Dwyer, Miss. Ellen "Nellie"                             female NA  0
30  Todoroff, Mr. Lalio                                       male   NA  0
⋮   ⋮                                                         ⋮      ⋮   ⋮
862 Giles, Mr. Frederick Edward                               male   21  1
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48  0
864 Sage, Miss. Dorothy Edith "Dolly"                         female NA  8
865 Gill, Mr. John William                                    male   24  0
866 Bystrom, Mrs. (Karolina)                                  female 42  0
867 Duran y More, Miss. Asuncion                              female 27  1
868 Roebling, Mr. Washington Augustus II                      male   31  0
869 van Melkebeke, Mr. Philemon                               male   NA  0
870 Johnson, Master. Harold Theodor                           male    4  1
871 Balkic, Mr. Cerin                                         male   26  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47  1
873 Carlsson, Mr. Frans Olof                                  male   33  0
874 Vander Cruyssen, Mr. Victor                               male   47  0
875 Abelson, Mrs. Samuel (Hannah Wizosky)                     female 28  1
876 Najib, Miss. Adele Kiamie "Jane"                          female 15  0
877 Gustafsson, Mr. Alfred Ossian                             male   20  0
878 Petroff, Mr. Nedelio                                      male   19  0
879 Laleff, Mr. Kristo                                        male   NA  0
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)             female 56  0
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25  0
882 Markun, Mr. Johann                                        male   33  0
883 Dahlberg, Miss. Gerda Ulrika                              female 22  0
884 Banfield, Mr. Frederick James                             male   28  0
885 Sutehall, Mr. Henry Jr                                    male   25  0
886 Rice, Mrs. William (Margaret Norton)                      female 39  0
887 Montvila, Rev. Juozas                                     male   27  0
888 Graham, Miss. Margaret Edith                              female 19  0
889 Johnston, Miss. Catherine Helen "Carrie"                  female NA  1
890 Behr, Mr. Karl Howell                                     male   26  0
891 Dooley, Mr. Patrick                                       male   32  0
    Parch Ticket           Fare     Cabin       Embarked
1   0     A/5 21171          7.2500 NA          S
2   0     PC 17599          71.2833 C85         C
3   0     STON/O2. 3101282   7.9250 NA          S
4   0     113803            53.1000 C123        S
5   0     373450             8.0500 NA          S
6   0     330877             8.4583 NA          Q
7   0     17463             51.8625 E46         S
8   1     349909            21.0750 NA          S
9   2     347742            11.1333 NA          S
10  0     237736            30.0708 NA          C
11  1     PP 9549           16.7000 G6          S
12  0     113783            26.5500 C103        S
13  0     A/5. 2151          8.0500 NA          S
14  5     347082            31.2750 NA          S
15  0     350406             7.8542 NA          S
16  0     248706            16.0000 NA          S
17  1     382652            29.1250 NA          Q
18  0     244373            13.0000 NA          S
19  0     345763            18.0000 NA          S
20  0     2649               7.2250 NA          C
21  0     239865            26.0000 NA          S
22  0     248698            13.0000 D56         S
23  0     330923             8.0292 NA          Q
24  0     113788            35.5000 A6          S
25  1     349909            21.0750 NA          S
26  5     347077            31.3875 NA          S
27  0     2631               7.2250 NA          C
28  2     19950            263.0000 C23 C25 C27 S
29  0     330959             7.8792 NA          Q
30  0     349216             7.8958 NA          S
⋮   ⋮     ⋮                ⋮        ⋮           ⋮
862 0     28134            11.5000  NA          S
863 0     17466            25.9292  D17         S
864 2     CA. 2343         69.5500  NA          S
865 0     233866           13.0000  NA          S
866 0     236852           13.0000  NA          S
867 0     SC/PARIS 2149    13.8583  NA          C
868 0     PC 17590         50.4958  A24         S
869 0     345777            9.5000  NA          S
870 1     347742           11.1333  NA          S
871 0     349248            7.8958  NA          S
872 1     11751            52.5542  D35         S
873 0     695               5.0000  B51 B53 B55 S
874 0     345765            9.0000  NA          S
875 0     P/PP 3381        24.0000  NA          C
876 0     2667              7.2250  NA          C
877 0     7534              9.8458  NA          S
878 0     349212            7.8958  NA          S
879 0     349217            7.8958  NA          S
880 1     11767            83.1583  C50         C
881 1     230433           26.0000  NA          S
882 0     349257            7.8958  NA          S
883 0     7552             10.5167  NA          S
884 0     C.A./SOTON 34068 10.5000  NA          S
885 0     SOTON/OQ 392076   7.0500  NA          S
886 5     382652           29.1250  NA          Q
887 0     211536           13.0000  NA          S
888 0     112053           30.0000  B42         S
889 2     W./C. 6607       23.4500  NA          S
890 0     111369           30.0000  C148        C
891 0     370376            7.7500  NA          Q

Si volem llegir un fitxer que no està separat per comes, utilitzarem la funció [`read_delim`](https://readr.tidyverse.org/reference/read_delim.html) i especificarem el separador amb el paràmetre `delim`.

In [2]:
df <- read_delim("data/titanic.tsv", delim='\t')
df

Parsed with column specification:
cols(
  PassengerId = col_integer(),
  Survived = col_integer(),
  Pclass = col_integer(),
  Name = col_character(),
  Sex = col_character(),
  Age = col_double(),
  SibSp = col_integer(),
  Parch = col_integer(),
  Ticket = col_character(),
  Fare = col_double(),
  Cabin = col_character(),
  Embarked = col_character()
)

    PassengerId Survived Pclass
1    1          0        3
2    2          1        1
3    3          1        3
4    4          1        1
5    5          0        3
6    6          0        3
7    7          0        1
8    8          0        3
9    9          1        3
10  10          1        2
11  11          1        3
12  12          1        1
13  13          0        3
14  14          0        3
15  15          0        3
16  16          1        2
17  17          0        3
18  18          1        2
19  19          0        3
20  20          1        3
21  21          0        2
22  22          1        2
23  23          1        3
24  24          1        1
25  25          0        3
26  26          1        3
27  27          0        3
28  28          0        1
29  29          1        3
30  30          0        3
⋮   ⋮           ⋮        ⋮
862 862         0        2
863 863         1        1
864 864         0        3
865 865         0        2
866 866         1        2
867 867         1        2
868 868         0        1
869 869         0        3
870 870         1        3
871 871         0        3
872 872         1        1
873 873         0        1
874 874         0        3
875 875         1        2
876 876         1        3
877 877         0        3
878 878         0        3
879 879         0        3
880 880         1        1
881 881         1        2
882 882         0        3
883 883         0        3
884 884         0        2
885 885         0        3
886 886         0        3
887 887         0        2
888 888         1        1
889 889         0        3
890 890         1        1
891 891         0        3
    Name                                                      Sex    Age SibSp
1   Braund, Mr. Owen Harris                                   male   22  1
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)       female 38  1
3   Heikkinen, Miss. Laina                                    female 26  0
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35  1
5   Allen, Mr. William Henry                                  male   35  0
6   Moran, Mr. James                                          male   NA  0
7   McCarthy, Mr. Timothy J                                   male   54  0
8   Palsson, Master. Gosta Leonard                            male    2  3
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27  0
10  Nasser, Mrs. Nicholas (Adele Achem)                       female 14  1
11  Sandstrom, Miss. Marguerite Rut                           female  4  1
12  Bonnell, Miss. Elizabeth                                  female 58  0
13  Saundercock, Mr. William Henry                            male   20  0
14  Andersson, Mr. Anders Johan                               male   39  1
15  Vestrom, Miss. Hulda Amanda Adolfina                      female 14  0
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55  0
17  Rice, Master. Eugene                                      male    2  4
18  Williams, Mr. Charles Eugene                              male   NA  0
19  Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)   female 31  1
20  Masselmani, Mrs. Fatima                                   female NA  0
21  Fynney, Mr. Joseph J                                      male   35  0
22  Beesley, Mr. Lawrence                                     male   34  0
23  McGowan, Miss. Anna "Annie"                               female 15  0
24  Sloper, Mr. William Thompson                              male   28  0
25  Palsson, Miss. Torborg Danira                             female  8  3
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38  1
27  Emir, Mr. Farred Chehab                                   male   NA  0
28  Fortune, Mr. Charles Alexander                            male   19  3
29  O'Dwyer, Miss. Ellen "Nellie"                             female NA  0
30  Todoroff, Mr. Lalio                                       male   NA  0
⋮   ⋮                                                         ⋮      ⋮   ⋮
862 Giles, Mr. Frederick Edward                               male   21  1
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48  0
864 Sage, Miss. Dorothy Edith "Dolly"                         female NA  8
865 Gill, Mr. John William                                    male   24  0
866 Bystrom, Mrs. (Karolina)                                  female 42  0
867 Duran y More, Miss. Asuncion                              female 27  1
868 Roebling, Mr. Washington Augustus II                      male   31  0
869 van Melkebeke, Mr. Philemon                               male   NA  0
870 Johnson, Master. Harold Theodor                           male    4  1
871 Balkic, Mr. Cerin                                         male   26  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47  1
873 Carlsson, Mr. Frans Olof                                  male   33  0
874 Vander Cruyssen, Mr. Victor                               male   47  0
875 Abelson, Mrs. Samuel (Hannah Wizosky)                     female 28  1
876 Najib, Miss. Adele Kiamie "Jane"                          female 15  0
877 Gustafsson, Mr. Alfred Ossian                             male   20  0
878 Petroff, Mr. Nedelio                                      male   19  0
879 Laleff, Mr. Kristo                                        male   NA  0
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)             female 56  0
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25  0
882 Markun, Mr. Johann                                        male   33  0
883 Dahlberg, Miss. Gerda Ulrika                              female 22  0
884 Banfield, Mr. Frederick James                             male   28  0
885 Sutehall, Mr. Henry Jr                                    male   25  0
886 Rice, Mrs. William (Margaret Norton)                      female 39  0
887 Montvila, Rev. Juozas                                     male   27  0
888 Graham, Miss. Margaret Edith                              female 19  0
889 Johnston, Miss. Catherine Helen "Carrie"                  female NA  1
890 Behr, Mr. Karl Howell                                     male   26  0
891 Dooley, Mr. Patrick                                       male   32  0
    Parch Ticket           Fare     Cabin       Embarked
1   0     A/5 21171          7.2500 NA          S
2   0     PC 17599          71.2833 C85         C
3   0     STON/O2. 3101282   7.9250 NA          S
4   0     113803            53.1000 C123        S
5   0     373450             8.0500 NA          S
6   0     330877             8.4583 NA          Q
7   0     17463             51.8625 E46         S
8   1     349909            21.0750 NA          S
9   2     347742            11.1333 NA          S
10  0     237736            30.0708 NA          C
11  1     PP 9549           16.7000 G6          S
12  0     113783            26.5500 C103        S
13  0     A/5. 2151          8.0500 NA          S
14  5     347082            31.2750 NA          S
15  0     350406             7.8542 NA          S
16  0     248706            16.0000 NA          S
17  1     382652            29.1250 NA          Q
18  0     244373            13.0000 NA          S
19  0     345763            18.0000 NA          S
20  0     2649               7.2250 NA          C
21  0     239865            26.0000 NA          S
22  0     248698            13.0000 D56         S
23  0     330923             8.0292 NA          Q
24  0     113788            35.5000 A6          S
25  1     349909            21.0750 NA          S
26  5     347077            31.3875 NA          S
27  0     2631               7.2250 NA          C
28  2     19950            263.0000 C23 C25 C27 S
29  0     330959             7.8792 NA          Q
30  0     349216             7.8958 NA          S
⋮   ⋮     ⋮                ⋮        ⋮           ⋮
862 0     28134            11.5000  NA          S
863 0     17466            25.9292  D17         S
864 2     CA. 2343         69.5500  NA          S
865 0     233866           13.0000  NA          S
866 0     236852           13.0000  NA          S
867 0     SC/PARIS 2149    13.8583  NA          C
868 0     PC 17590         50.4958  A24         S
869 0     345777            9.5000  NA          S
870 1     347742           11.1333  NA          S
871 0     349248            7.8958  NA          S
872 1     11751            52.5542  D35         S
873 0     695               5.0000  B51 B53 B55 S
874 0     345765            9.0000  NA          S
875 0     P/PP 3381        24.0000  NA          C
876 0     2667              7.2250  NA          C
877 0     7534              9.8458  NA          S
878 0     349212            7.8958  NA          S
879 0     349217            7.8958  NA          S
880 1     11767            83.1583  C50         C
881 1     230433           26.0000  NA          S
882 0     349257            7.8958  NA          S
883 0     7552             10.5167  NA          S
884 0     C.A./SOTON 34068 10.5000  NA          S
885 0     SOTON/OQ 392076   7.0500  NA          S
886 5     382652           29.1250  NA          Q
887 0     211536           13.0000  NA          S
888 0     112053           30.0000  B42         S
889 2     W./C. 6607       23.4500  NA          S
890 0     111369           30.0000  C148        C
891 0     370376            7.7500  NA          Q

Per tornar-lo a guardar en un altre fitxer, per exemple separat per punts i coma, farem servir la funció [`write_csv`](https://readr.tidyverse.org/reference/write_delim.html) de `readr`.

In [3]:
write_csv(df, 'data/titanic_semicolon.csv')

##  Fitxers Excel

Tot i ser un programari propietari, `Excel` és una de les eines més populars i utilitzades en el tractament de dades. [`readxl`](https://readxl.tidyverse.org/) és capaç de llegir els fitxers que genera aquest programari en les seves diferents versions.

El fitxer `Excel` que llegirem correspon al dataset de la competició [TMDB 5000 Movie Dataset](https://www.kaggle.com/tmdb/tmdb-movie-metadata) de [Kaggle](https://www.kaggle.com/). Aquest excel té tres `sheets` que corresponen a les películes dels anys `1900s`, `2000s` i `2010s`.

Per llegir un fitxer `Excel` farem servir la funció [`read_excel`](https://readxl.tidyverse.org/reference/read_excel.html) de [`readxl`](https://readxl.tidyverse.org/).

In [4]:
library(readxl)
xls_file <- read_excel("data/movies.xls")
xls_file

     Title                                             Year
1    Intolerance: Love's Struggle Throughout the Ages  1916
2    Over the Hill to the Poorhouse                    1920
3    The Big Parade                                    1925
4    Metropolis                                        1927
5    Pandora's Box                                     1929
6    The Broadway Melody                               1929
7    Hell's Angels                                     1930
8    A Farewell to Arms                                1932
9    42nd Street                                       1933
10   She Done Him Wrong                                1933
11   It Happened One Night                             1934
12   Top Hat                                           1935
13   Modern Times                                      1936
14   The Charge of the Light Brigade                   1936
15   Snow White and the Seven Dwarfs                   1937
16   The Prisoner of Zenda                             1937
17   Alexander's Ragtime Band                          1938
18   You Can't Take It with You                        1938
19   Gone with the Wind                                1939
20   Mr. Smith Goes to Washington                      1939
21   The Wizard of Oz                                  1939
22   Boom Town                                         1940
23   Fantasia                                          1940
24   Pinocchio                                         1940
25   Rebecca                                           1940
26   The Blue Bird                                     1940
27   How Green Was My Valley                           1941
28   Bambi                                             1942
29   Casablanca                                        1942
30   A Guy Named Joe                                   1943
⋮    ⋮                                                 ⋮
1309 The Limey                                         1999
1310 The Loss of Sexual Innocence                      1999
1311 The Matrix                                        1999
1312 The Messenger: The Story of Joan of Arc           1999
1313 The Muse                                          1999
1314 The Ninth Gate                                    1999
1315 The Omega Code                                    1999
1316 The Out-of-Towners                                1999
1317 The Rage: Carrie 2                                1999
1318 The Sixth Sense                                   1999
1319 The Story of Us                                   1999
1320 The Straight Story                                1999
1321 The Talented Mr. Ripley                           1999
1322 The Thirteenth Floor                              1999
1323 The Thomas Crown Affair                           1999
1324 The Virgin Suicides                               1999
1325 The Woman Chaser                                  1999
1326 The Wood                                          1999
1327 The World Is Not Enough                           1999
1328 Three Kings                                       1999
1329 Three to Tango                                    1999
1330 Topsy-Turvy                                       1999
1331 Toy Story 2                                       1999
1332 Trippin'                                          1999
1333 Tumbleweeds                                       1999
1334 Twin Falls Idaho                                  1999
1335 Universal Soldier: The Return                     1999
1336 Varsity Blues                                     1999
1337 Wild Wild West                                    1999
1338 Wing Commander                                    1999
     Genres                                       Language Country
1    Drama|History|War                            NA       USA
2    Crime|Drama                                  NA       USA
3    Drama|Romance|War                            NA       USA
4    Drama|Sci-Fi                                 German   Germany
5    Crime|Drama|Romance                          German   Germany
6    Musical|Romance                              English  USA
7    Drama|War                                    English  USA
8    Drama|Romance|War                            English  USA
9    Comedy|Musical|Romance                       English  USA
10   Comedy|Drama|History|Musical|Romance         English  USA
11   Comedy|Romance                               English  USA
12   Comedy|Musical|Romance                       English  USA
13   Comedy|Drama|Family                          English  USA
14   Action|Adventure|Romance|War                 English  USA
15   Animation|Family|Fantasy|Musical             English  USA
16   Adventure|Drama|Romance                      English  USA
17   Drama|Musical|Romance                        English  USA
18   Comedy|Drama|Romance                         English  USA
19   Drama|History|Romance|War                    English  USA
20   Comedy|Drama                                 English  USA
21   Adventure|Family|Fantasy|Musical             English  USA
22   Adventure|Drama|Romance|Western              English  USA
23   Animation|Family|Fantasy|Music               English  USA
24   Animation|Family|Fantasy|Musical             English  USA
25   Drama|Film-Noir|Mystery|Thriller             English  USA
26   Drama|Family|Fantasy                         English  USA
27   Drama|Family                                 English  USA
28   Animation|Drama|Family                       English  USA
29   Drama|Romance|War                            English  USA
30   Drama|Fantasy|Romance|War                    English  USA
⋮    ⋮                                            ⋮        ⋮
1309 Crime|Drama|Mystery|Thriller                 English  USA
1310 Drama                                        English  USA
1311 Action|Sci-Fi                                English  USA
1312 Adventure|Biography|Drama|History|War        English  France
1313 Comedy                                       English  USA
1314 Mystery|Thriller                             English  Spain
1315 Action|Adventure|Fantasy|Sci-Fi|Thriller     English  USA
1316 Comedy                                       English  USA
1317 Horror|Sci-Fi|Thriller                       English  USA
1318 Drama|Mystery|Thriller                       English  USA
1319 Comedy|Drama|Romance                         English  USA
1320 Biography|Drama                              English  France
1321 Crime|Drama|Thriller                         English  USA
1322 Mystery|Sci-Fi|Thriller                      English  Germany
1323 Crime|Romance|Thriller                       English  USA
1324 Drama|Romance                                English  USA
1325 Comedy                                       English  USA
1326 Comedy|Drama|Romance                         English  USA
1327 Action|Adventure|Thriller                    English  UK
1328 Action|Adventure|Comedy|Drama|War            English  USA
1329 Comedy|Romance                               English  Australia
1330 Biography|Comedy|Drama|History|Music|Musical English  UK
1331 Adventure|Animation|Comedy|Family|Fantasy    English  USA
1332 Comedy                                       English  USA
1333 Comedy|Drama                                 English  USA
1334 Drama                                        English  USA
1335 Action|Sci-Fi                                English  USA
1336 Comedy|Drama|Romance|Sport                   English  USA
1337 Action|Comedy|Sci-Fi|Western                 English  USA
1338 Action|Adventure|Sci-Fi                      English  USA
     Content Rating Duration Aspect Ratio Budget   Gross Earnings ⋯
1    Not Rated      123      1.33          385907         NA      ⋯
2    NA             110      1.33          100000    3000000      ⋯
3    Not Rated      151      1.33          245000         NA      ⋯
4    Not Rated      145      1.33         6000000      26435      ⋯
5    Not Rated      110      1.33              NA       9950      ⋯
6    Passed         100      1.37          379000    2808000      ⋯
7    Passed          96      1.20         3950000         NA      ⋯
8    Unrated         79      1.37          800000         NA      ⋯
9    Unrated         89      1.37          439000    2300000      ⋯
10   Approved        66      1.37          200000         NA      ⋯
11   Unrated         65      1.37          325000         NA      ⋯
12   Approved        81      1.37          609000    3000000      ⋯
13   G               87      1.37         1500000     163245      ⋯
14   Approved       100      1.37         1200000         NA      ⋯
15   Approved        83      1.37         2000000  184925485      ⋯
16   Approved       101      1.37              NA         NA      ⋯
17   Approved       106      1.37         2000000         NA      ⋯
18   Approved       126      1.37         1644736         NA      ⋯
19   G              226      1.37         3977000  198655278      ⋯
20   Not Rated      120      1.37         1500000         NA      ⋯
21   Passed         102      1.37         2800000   22202612      ⋯
22   Passed         119      1.37         1614000         NA      ⋯
23   G              120      1.37         2280000   76400000      ⋯
24   Approved        88      1.37         2600000   84300000      ⋯
25   Not Rated      130      1.37         1288000         NA      ⋯
26   Approved        83      1.37              NA         NA      ⋯
27   Approved       118      1.37         1250000         NA      ⋯
28   Approved        70      1.33              NA  102797150      ⋯
29   PG              82      1.37          950000         NA      ⋯
30   Passed         122      1.37         2627000         NA      ⋯
⋮    ⋮              ⋮        ⋮            ⋮        ⋮              ⋱
1309 R               89      1.85         9.00e+06   3193102      ⋯
1310 R              106      1.78         4.00e+06    399793      ⋯
1311 R              136      2.35         6.30e+07 171383253      ⋯
1312 R              158      2.35         3.90e+08  14131298      ⋯
1313 PG-13           97      1.37         1.50e+07  11614236      ⋯
1314 R              133      2.35         3.80e+07  18653746      ⋯
1315 PG-13          100      1.37         7.50e+06  12610552      ⋯
1316 PG-13           90      1.85         4.00e+07  28535768      ⋯
1317 R              104      1.85         2.10e+07  17757087      ⋯
1318 PG-13          107      1.85         4.00e+07 293501675      ⋯
1319 R               95      1.85         5.00e+07  27067160      ⋯
1320 G              112      2.35         1.00e+07   6197866      ⋯
1321 R              139      1.85         4.00e+07  81292135      ⋯
1322 R              100      2.35         1.60e+07  15500000      ⋯
1323 R              113      2.35         4.80e+07  69304264      ⋯
1324 R               90      1.85         6.00e+06   4859475      ⋯
1325 NA              88        NA         1.20e+06    110720      ⋯
1326 R              106      1.85         6.00e+06  25047631      ⋯
1327 PG-13          128      2.35         1.35e+08 126930660      ⋯
1328 R              114      2.35         4.80e+07  60652036      ⋯
1329 PG-13           98      1.37         2.00e+07  10544143      ⋯
1330 R              154      1.66         1.00e+07   6201757      ⋯
1331 G               82      1.85         9.00e+07 245823397      ⋯
1332 R               94      1.85               NA   9016377      ⋯
1333 PG-13          102      1.85         3.12e+05   1281176      ⋯
1334 R              111      1.85         5.00e+05    985341      ⋯
1335 R               83      1.85         2.40e+07  10431220      ⋯
1336 R              106      1.85         1.60e+07  52885587      ⋯
1337 PG-13          106      1.85         1.70e+08 113745408      ⋯
1338 PG-13          100      2.35         3.00e+07  11576087      ⋯
     Facebook Likes - Actor 1 Facebook Likes - Actor 2 Facebook Likes - Actor 3
1     436                      22                        9
2       2                       2                        0
3      81                      12                        6
4     136                      23                       18
5     426                      20                        3
6      77                      28                        4
7     431                      12                        4
8     998                     164                       99
9     610                     105                       45
10    418                      85                       28
11    380                     114                       21
12    610                     172                       23
13    309                       8                        8
14    843                     490                       94
15     82                      47                       31
16    490                     185                      135
17    480                     392                      300
18    319                     302                      275
19    503                     384                      248
20    607                     319                      248
21    695                     421                      357
22   1000                     760                      380
23     16                       0                       NA
24   1000                      48                       40
25   1000                     991                      333
26     94                      62                       51
27    595                     176                      137
28     16                      12                        8
29   2000                     607                      269
30    760                     675                      315
⋮    ⋮                        ⋮                        ⋮
1309   402                      296                     132
1310  2000                      811                     687
1311 18000                      145                      99
1312    51                       40                      15
1313 12000                      821                     745
1314 40000                      903                     541
1315   488                      488                     440
1316   607                      322                     210
1317   711                      490                     484
1318 13000                     3000                     766
1319 13000                      559                     323
1320   874                      262                     201
1321 22000                    13000                    1000
1322   599                      380                     363
1323  1000                      977                     835
1324  4000                      899                     826
1325   142                       23                       3
1326   865                      405                     328
1327   766                      536                     244
1328  2000                      490                     393
1329  2000                     1000                     677
1330  1000                      452                     149
1331 15000                     1000                     967
1332   927                      209                     200
1333   409                      277                     276
1334   980                      505                     482
1335  2000                      577                     485
1336 23000                      255                      35
1337 10000                     4000                     582
1338   811                      586                     362
     Facebook Likes - cast Total Facebook likes - Movie Facenumber in posters
1     481                          691                   1
2       4                            0                   1
3     108                          226                   0
4     203                        12000                   1
5     455                          926                   1
6     109                          167                   8
7     457                          279                   1
8    1284                          213                   1
9     995                          439                   2
10    583                          328                   1
11    540                            0                   1
12    824                         1000                   2
13    352                            0                   1
14   1621                          204                   3
15    229                            0                   1
16   1166                          337                   2
17   1833                           60                   2
18   1363                            0                  10
19   1862                        16000                   1
20   1573                            0                   7
21   2509                        14000                   3
22   2555                          236                   8
23     16                         3000                   0
24   1178                            0                   0
25   2888                            0                   2
26    293                          548                   1
27   1129                            0                   5
28     63                            0                   0
29   3442                        23000                   4
30   2555                          116                   0
⋮    ⋮                           ⋮                      ⋮
1309  1335                         944                  0
1310  4343                         111                  0
1311 18563                       25000                  3
1312   144                           0                  0
1313 15209                         251                  2
1314 42344                           0                  1
1315  2428                         129                  0
1316  1335                         279                  2
1317  3162                         897                  1
1318 17540                       14000                  0
1319 14706                           0                  1
1320  1351                           0                  0
1321 36810                           0                  1
1322  2389                           0                  0
1323  4660                           0                  0
1324  7103                           0                  0
1325   168                          73                  0
1326  2724                         990                  0
1327  2037                        2000                  2
1328  3743                        3000                  1
1329  4843                         311                  2
1330  1690                         608                  1
1331 21275                           0                  2
1332  1936                         143                  3
1333  1986                         121                  1
1334  3166                         180                  0
1335  4024                         401                  0
1336 23369                           0                  0
1337 15870                           0                  2
1338  2497                         858                  3
     User Votes Reviews by Users Reviews by Crtiics IMDB Score
1     10718       88              69                8.0
2         5        1               1                4.8
3      4849       45              48                8.3
4    111841      413             260                8.3
5      7431       84              71                8.0
6      4546       71              36                6.3
7      3753       53              35                7.8
8      3519       46              42                6.6
9      7921       97              65                7.7
10     4152       59              35                6.5
11    64888      235             124                8.2
12    13269       98              66                7.8

El nostre `Excel` té tres `sheets`. Si no li diem res, per defecte la funció [`read_excel`](https://readxl.tidyverse.org/reference/read_excel.html) ens carrega el primer. Si volem veure quins `sheets` té, podem fer servir la funció [`excel_sheets`](https://readxl.tidyverse.org/reference/excel_sheets.html).

In [5]:
excel_sheets("data/movies.xls")

[1] "1900s" "2000s" "2010s"

I a continuació podem especificar que n'obri un altre amb el paràmetre `sheet`.

In [6]:
xls_file <- read_excel("data/movies.xls", sheet = "2010s")
xls_file

     Title                                     Year
1    127 Hours                                 2010
2    3 Backyards                               2010
3    3                                         2010
4    8: The Mormon Proposition                 2010
5    A Turtle's Tale: Sammy's Adventures       2010
6    Alice in Wonderland                       2010
7    Alice in Wonderland                       2010
8    All Good Things                           2010
9    Alpha and Omega                           2010
10   Amigo                                     2010
11   Anderson's Cross                          2010
12   Animals United                            2010
13   Another Year                              2010
14   Barney's Version                          2010
15   Barry Munday                              2010
16   Beginners                                 2010
17   Beneath Hill 60                           2010
18   Beyond the Black Rainbow                  2010
19   Biutiful                                  2010
20   Black Swan                                2010
21   Blood Done Sign My Name                   2010
22   Blue Valentine                            2010
23   Brighton Rock                             2010
24   Buried                                    2010
25   Burlesque                                 2010
26   Ca$h                                      2010
27   Casino Jack                               2010
28   Cats & Dogs: The Revenge of Kitty Galore  2010
29   Centurion                                 2010
30   Charlie St. Cloud                         2010
⋮    ⋮                                         ⋮
1575 The Bold and the Beautiful                NA
1576 The Border                                NA
1577 The Company                               NA
1578 The Dead Zone                             NA
1579 The Doombolt Chase                        NA
1580 The Family                                NA
1581 The Following                             NA
1582 The Girlfriend Experience                 NA
1583 The Grand                                 NA
1584 The Honeymooners                          NA
1585 The Inbetweeners                          NA
1586 The Messengers                            NA
1587 The Missing                               NA
1588 The O.C.                                  NA
1589 The Player                                NA
1590 The Powerpuff Girls                       NA
1591 The Returned                              NA
1592 The Secret                                NA
1593 The Streets of San Francisco              NA
1594 Towering Inferno                          NA
1595 Trapped                                   NA
1596 Twisted                                   NA
1597 Unforgettable                             NA
1598 Unforgotten                               NA
1599 Veronica Mars                             NA
1600 War & Peace                               NA
1601 Wings                                     NA
1602 Wolf Creek                                NA
1603 Wuthering Heights                         NA
1604 Yu-Gi-Oh! Duel Monsters                   NA
     Genres                                        Language  Country
1    Adventure|Biography|Drama|Thriller            English   USA
2    Drama                                         English   USA
3    Comedy|Drama|Romance                          German    Germany
4    Documentary                                   English   USA
5    Adventure|Animation|Family                    English   France
6    Adventure|Family|Fantasy                      English   USA
7    Adventure|Family|Fantasy                      English   USA
8    Crime|Drama|Mystery|Romance|Thriller          English   USA
9    Adventure|Animation|Comedy|Family|Romance     English   USA
10   Drama|War                                     English   USA
11   Comedy|Drama|Romance                          English   USA
12   Animation|Comedy|Family                       German    Germany
13   Comedy|Drama                                  English   UK
14   Comedy|Drama                                  English   Canada
15   Comedy|Drama|Romance                          English   USA
16   Comedy|Drama|Romance                          English   USA
17   Drama|History|War                             English   Australia
18   Sci-Fi|Thriller                               English   Canada
19   Drama                                         Spanish   Mexico
20   Drama|Thriller                                English   USA
21   Drama                                         English   USA
22   Drama|Romance                                 English   USA
23   Crime|Drama|Thriller                          English   UK
24   Drama|Mystery|Thriller                        English   Spain
25   Drama|Music|Musical|Romance                   English   USA
26   Comedy|Crime|Thriller                         English   USA
27   Biography|Comedy|Crime|Drama                  English   Canada
28   Action|Comedy|Family|Fantasy                  English   USA
29   Action|Adventure|Drama|History|Thriller|War   English   UK
30   Drama|Fantasy|Romance                         English   USA
⋮    ⋮                                             ⋮         ⋮
1575 Drama|Romance                                 English   USA
1576 Action|Crime|Drama|Thriller                   Polish    Poland
1577 Drama|History|Thriller                        English   USA
1578 Drama|Fantasy|Mystery|Sci-Fi                  English   Canada
1579 Drama|Family                                  English   UK
1580 Drama|Mystery                                 English   USA
1581 Crime|Drama|Mystery|Thriller                  English   USA
1582 Drama                                         English   USA
1583 Drama                                         English   UK
1584 Comedy|Family                                 English   USA
1585 Comedy|Romance                                English   UK
1586 Drama|Fantasy|Mystery|Thriller                English   USA
1587 Crime|Drama|Mystery                           English   UK
1588 Comedy|Drama|Romance                          English   USA
1589 Action|Crime|Drama|Thriller                   English   USA
1590 Action|Animation|Comedy|Family|Fantasy|Sci-Fi English   USA
1591 Drama|Fantasy|Horror|Mystery                  French    France
1592 Drama|Thriller                                English   UK
1593 Action|Crime|Drama|Mystery                    English   USA
1594 Comedy                                        English   Canada
1595 Crime|Drama|Thriller                          Icelandic Iceland
1596 Drama|Mystery|Thriller                        English   USA
1597 Drama|Mystery                                 NA        USA
1598 Crime|Drama                                   English   UK
1599 Crime|Drama|Mystery                           English   USA
1600 Drama|History|Romance|War                     English   UK
1601 Comedy|Drama                                  English   USA
1602 Drama|Horror|Thriller                         English   Australia
1603 Drama|Romance                                 English   UK
1604 Action|Adventure|Animation|Family|Fantasy     Japanese  Japan
     Content Rating Duration Aspect Ratio Budget  Gross Earnings ⋯
1    R               94      1.85         1.8e+07  18329466      ⋯
2    R               88        NA         3.0e+05        NA      ⋯
3    Unrated        119      2.35              NA     59774      ⋯
4    R               80      1.78         2.5e+06     99851      ⋯
5    PG              88      2.35              NA        NA      ⋯
6    PG             108      1.85         2.0e+08 334185206      ⋯
7    PG             108      1.85         2.0e+08 334185206      ⋯
8    R              101      1.85              NA    578382      ⋯
9    PG              90      1.85         2.0e+07  25077977      ⋯
10   R              124        NA         1.7e+06    183490      ⋯
11   R               98        NA         3.0e+05        NA      ⋯
12   PG              93      2.39              NA        NA      ⋯
13   PG-13          129      2.35         1.0e+07   3205244      ⋯
14   R              134      2.35              NA   7501404      ⋯
15   R               95      1.85              NA        NA      ⋯
16   R              105      1.85         3.2e+06   5776314      ⋯
17   R              122      2.35         9.0e+06        NA      ⋯
18   R              110      2.35         1.1e+06     56129      ⋯
19   R              148      2.35              NA   5100937      ⋯
20   R              108      2.35         1.3e+07 106952327      ⋯
21   PG-13          128      2.35              NA     82739      ⋯
22   R              112      1.66         3.5e+06   9701559      ⋯
23   R              111      2.35         1.2e+07        NA      ⋯
24   R               95      2.35         3.0e+06   1028658      ⋯
25   PG-13          119      2.35         5.5e+07  39440655      ⋯
26   R              118      1.85         7.0e+06     46451      ⋯
27   R              108      2.35         1.5e+07   1039869      ⋯
28   PG              82      1.85         8.5e+07  43575716      ⋯
29   R               97      2.35              NA    122288      ⋯
30   PG-13           99      2.35         4.4e+07  31136950      ⋯
⋮    ⋮              ⋮        ⋮            ⋮       ⋮              ⋱
1575 TV-14           30       1.78        NA      NA             ⋯
1576 NA              41         NA        NA      NA             ⋯
1577 NA             286       1.78        NA      NA             ⋯
1578 TV-14           60         NA        NA      NA             ⋯
1579 NA              30         NA        NA      NA             ⋯
1580 TV-PG           60      16.00        NA      NA             ⋯
1581 TV-14           43      16.00        NA      NA             ⋯
1582 TV-MA           27         NA        NA      NA             ⋯
1583 NA              60       1.33        NA      NA             ⋯
1584 NA              30       1.33        NA      NA             ⋯
1585 TV-14           25      16.00        NA      NA             ⋯
1586 NA              60      16.00        NA      NA             ⋯
1587 NA              60         NA        NA      NA             ⋯
1588 TV-PG           44       1.78        NA      NA             ⋯
1589 TV-14           60      16.00        NA      NA             ⋯
1590 TV-Y7           30       4.00        NA      NA             ⋯
1591 TV-MA           52      16.00        NA      NA             ⋯
1592 NA              45         NA        NA      NA             ⋯
1593 NA             120       4.00        NA      NA             ⋯
1594 NA              65       1.33        NA      NA             ⋯
1595 NA             511      16.00        NA      NA             ⋯
1596 NA              60      16.00        NA      NA             ⋯
1597 NA              60         NA        NA      NA             ⋯
1598 NA              45         NA        NA      NA             ⋯
1599 TV-14           44       1.78        NA      NA             ⋯
1600 TV-14           NA      16.00        NA      NA             ⋯
1601 NA              30       1.33        NA      NA             ⋯
1602 NA              NA       2.00        NA      NA             ⋯
1603 NA             142         NA        NA      NA             ⋯
1604 NA              24         NA        NA      NA             ⋯
     Facebook Likes - Actor 1 Facebook Likes - Actor 2 Facebook Likes - Actor 3
1    11000                      642                      223
2      795                      659                      301
3       24                       20                        9
4      191                       12                        5
5      783                      749                      602
6    40000                    25000                    11000
7    40000                    25000                    11000
8    33000                     4000                      902
9      681                      611                      518
10      38                        8                        7
11     500                      317                      248
12    1000                      898                      480
13    1000                      579                      386
14     891                      460                      329
15    2000                      536                      463
16    1000                      394                      157
17     174                      109                       59
18     434                       95                       48
19      30                        9                        7
20   20000                    15000                     1000
21     665                      664                      553
22   33000                     2000                      616
23     845                      641                      405
24   16000                      517                      263
25    2000                      828                      676
26   26000                      854                      410
27   18000                      322                      168
28     975                      760                      615
29   13000                      794                      570
30     405                      268                      135
⋮    ⋮                        ⋮                        ⋮
1575   177                    170                      140
1576    70                      2                        2
1577   857                    555                      527
1578   443                    319                      186
1579   310                     11                        9
1580   971                    805                      468
1581   841                    593                      319
1582   934                    691                      201
1583    40                     37                       23
1584   491                    154                       94
1585   229                    223                      220
1586  1000                    921                      762
1587  1000                    773                      575
1588   828                    787                      650
1589   666                    579                      460
1590   971                    918                      265
1591   164                    116                      114
1592   773                    133                      119
1593   416                      0                       NA
1594   770                    179                      176
1595   147                     63                       51
1596   629                    512                      398
1597   654                    426                      405
1598   416                    171                      132
1599   937                    828                      724
1600  1000                    888                      502
1601   685                    511                      424
1602   511                    457                      206
1603 27000                    698                      427
1604     0                     NA                       NA
     Facebook Likes - cast Total Facebook likes - Movie Facenumber in posters
1    11984                        63000                  0
2     1884                           92                  0
3       69                         2000                  0
4      210                            0                  0
5     3874                            0                  2
6    79957                        24000                  0
7    79957                        24000                  0
8    39515                            0                  2
9     2486                            0                  0
10      60                          594                  0
11    1545                            7                  7
12    3095                          885                  0
13    2265                            0                  0
14    1873                            0                  2
15    3648                          480                  2
16    2016                        15000                  4
17     498                            0                 12
18     645                            0                  1
19      50                        29000                  0
20   38072                       106000                  1
21    4579                          503                  0
22   35941                        25000                  0
23    3117                            0                  2
24   17471                        24000                  0
25    4315                        19000                  1
26   27756                          694                  2
27   18739                            0                  5
28    3326                            0                  0
29   15293                            0                  0
30    1066                            0                  1
⋮    ⋮                           ⋮                      ⋮
1575   639                         748                  0
1576    74                          64                  4
1577  3809                         733                  3
1578   981                         576                  1
1579   344                           0                  4
1580  3295                           0                  4
1581  1753                       32000                  1
1582  1961                         632                  0
1583   158                         450                  0
1584   812                         459                  4
1585  1239                           0                  0
1586  4561                           0                  0
1587  3537                           0                  0
1588  2546                           0                  8
1589  4043                           0                  2
1590  2346                         581                  0
1591   654                       17000                  9
1592  1393                         405                  3
1593   416                         533                  0
1594  1125                           0                  2
1595   307                           0                  0
1596  2758                         915                  2
1597  1906                           0                  1
1598  1816                           0                  2
1599  3318                           0                  1
1600  4528                       11000                  1
1601  1884                        1000                  5
1602  1617                         954                  0
1603 29196                           0                  2
1604     0                         124                  0
     User Votes Reviews by Users Reviews by Crtiics IMDB Score
1    279179      440             450                7.6
2       554       23              20                5.2
3      4212       18              76                6.8
4      1138       30              28                7.1
5      5385       22              56                6.1
6    306320      736             451                6.5
7    306336      736             451                6.5
8     41249       67             140                6.3
9     10986       84              84                5.3
10      463        8              35                5.8
11       95        7               8                7.2
12     4599       44              36                4.9
13    23629      141             248                7.3
14    21086       87             193                7.3
15     3443       20              34                5.9
16    73349      142             261                7.2
17     5741       39              17                7.1
18     6555       82              97                6.1
19    68885      127             288                7.5
20   551363     1140             669                8.0

Per tornar-lo a guardar en un altre fitxer `Excel` farem servir la funció  [`write.xlsx`](https://rdrr.io/cran/openxlsx/man/write.xlsx.html) de `openxlsx`.

In [7]:
openxlsx::write.xlsx(xls_file, file = "data/movies_2010.xlsx")

<!--Footer-->
 <div style="background: #333333;padding: 35px 0px;margin-top: 25px;">
    <div class="row">
     <div class="col-sm-12">
        <img src="http://materials.cv.uoc.edu/cdocent/common/img/logo-uoc-bottom.png" alt="Logo UOC" class="img-responsive" style="margin: 0 auto; display: block;">
    </div>
</div>
</div>
<!--/Footer-->